version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - .:/srv
volumes:
  data: